[package]
name = "kvarn-chute"
version = "0.1.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2021"
rust-version = "1.56"
description = "A MarkDown converter designed to use the Kvarn templating engine."
readme = "README.md"
homepage = "https://kvarn.org/chute/"
repository = "https://github.com/Icelk/kvarn/"
license = "MIT OR Apache-2.0"
keywords = ["markdown", "kvarn-extension", "kvarn", "templates"]
categories = ["command-line-utilities", "text-processing"]

[dependencies]
pulldown-cmark = { version = "^0.9", default-features = false, features = ["simd"] }
notify = "^4"
unicode_categories = "^0.1"
chrono = { version = "^0.4.19", optional = true }

[features]
default = ["date"]
date = ["chrono"]
