[package]
name = "kvarn"
version = "0.2.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2018"
description = "An extensible and forward-thinking web server for the future."
homepage = "https://kvarn.org/"
repository = "https://github.com/Icelk/kvarn/"
license = "Apache-2.0"
keywords = ["web", "web-server", "web-application", "web-framework"]
categories = ["web-programming", "web-programming::http-server"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "./",
  "kvarn_extensions",
  "kvarn_chute",
]

[dependencies]
bytes = "^1"
rustls = { version = "^0.19", optional = true }
webpki = { version = "^0.21", optional = true }
tokio = { version = "^1", features = ["rt", "io-util", "net", "fs", "sync", "parking_lot", "time"] }
futures = "^0.3"
log = "^0.4"
http = "^0.2"
mime = "^0.3"
mime_guess = "^2"
brotli = { version = "^3", optional = true }
flate2 = { version = "^1", optional = true }
h2 = { version = "^0.3", default-features = false, optional = true }

[features]
default = ["https", "http2", "compression", "fs", "limiting"]

# Enables the server to serve from the file system
fs = []
# Enables limits on the server, to avoid abusive usage by counting IP requests
limiting = []

# Disables the cache
no-fs-cache = []
no-response-cache = []
no-cache = ["no-fs-cache", "no-response-cache"]

# Compressing
compression = ["br", "gzip"]
br = ["brotli"]
gzip = ["flate2"]

# HTTP standards
https = ["rustls", "webpki"]
http2 = ["h2", "https"]

# Multi threading
mt = ["tokio/rt-multi-thread"]
