[package]
name = "arktis"
version = "0.1.0"
authors = ["Iselk <62830417+Iselk@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.18.1"
http = "0.2.1"
mime_guess = "2.0.3"
