[package]
name = "kvarn"
version = "0.2.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2018"
description = "An extensible and forward-thinking web server for the future."
homepage = "https://kvarn.org/"
repository = "https://github.com/Icelk/kvarn/"
license = "Apache-2.0"
keywords = ["web", "web-server", "web-application", "web-framework"]
categories = ["web-programming", "web-programming::http-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "./",
  "extensions",
  "chute",
  "utils",
  "async",
  "testing",
]

[dependencies]
brotli = { version = "^3", optional = true }
bytes = "^1"
chrono = "^0.4"
flate2 = { version = "^1", optional = true }
futures = "^0.3"
h2 = { version = "^0.3", default-features = false, optional = true }
http = "^0.2"
kvarn_utils = { path = "utils" }
kvarn_async = { path = "async" }
log = "^0.4"
mime = "^0.3"
mime_guess = "^2"
percent-encoding = "^2.1.0"
rustls = { version = "^0.19", optional = true }
tokio = { version = "^1", features = ["rt", "io-util", "net", "fs", "sync", "parking_lot", "time"] }
webpki = { version = "^0.21", optional = true }

[features]
default = ["all-http", "all-compression", "graceful-shutdown"]

# Enable all features
full = ["all-http", "all-compression", "graceful-shutdown", "mt"]

# All HTTP versions and features
all-http = ["https", "http2"]

# Compressing
all-compression = ["br", "gzip"]
br = ["brotli"]
gzip = ["flate2"]

# HTTP standards
https = ["rustls", "webpki"]
http2 = ["h2", "https"]

# Multi threading
mt = ["tokio/rt-multi-thread"]

# Graceful shutdown; shutdown.rs
graceful-shutdown = []

[dev-dependencies]
kvarn_testing = { path = "testing" }
