[package]
name = "kvarn"
version = "0.1.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2018"
homepage = "https://icelk.dev/kvarn/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "./",
  "kvarn_extensions",
  "kvarn_chute",
]

[dependencies]
rustls = "0.18"
http = "0.2"
mime_guess = "2"
mio = { version = "0.7", features = ["os-poll", "tcp"] }
num_cpus = "1.13"
mime = "0.3"
brotli = { version = "3.3", optional = true }
flate2 = { version = "1", optional = true }

[features]
default = ["compression", "fs", "limiting", "log"]

# Enable logging
log = ["info-log", "error-log"]
error-log = []
info-log = []
# Enables performance monitoring
performance-monitoring = []

# Enables the server to serve from the file system
fs = []
# Enables limits on the server, to avoid abusive usage by counting IP requests
limiting = []

# Disables the cache
no-fs-cache = []
no-response-cache = []
no-template-cache = []
no-cache = ["no-fs-cache", "no-response-cache", "no-template-cache"]

# Compressing
compression = ["br", "gzip"]
br = ["brotli"]
gzip = ["flate2"]
