[package]
name = "kvarn"
version = "0.3.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2021"
rust-version = "1.56"
description = "A forward-thinking fast web server designed to fit your needs, efficiently."
# main branch documentation
# documentation = "https://doc.kvarn.org/kvarn/"
readme = "README.md"
homepage = "https://kvarn.org/"
repository = "https://github.com/Icelk/kvarn/"
license = "Apache-2.0"
keywords = ["web", "web-server", "web-application", "web-framework"]
categories = ["web-programming", "web-programming::http-server"]

[workspace]
members = [
  "./",
  "extensions",
  "chute",
  "utils",
  "async",
  "url-crawl",
  "testing",
]

[dependencies]
base64 = { version = "0.13", optional = true }
brotli = { version = "3", optional = true }
bytes = "1"
flate2 = { version = "1", optional = true }
futures = "0.3"
h2 = { version = "0.3", default-features = false, optional = true }
http = "0.2"
kvarn_async = { path = "async", version = "0.3" }
kvarn_utils = { path = "utils", version = "0.3" }
log = "0.4"
memchr = { version = "2", optional = true }
mime = "0.3"
mime_guess = "2"
percent-encoding = "2"
rand = { version = "0.8", optional = true, features = ["small_rng"] }
rustls = { version = "0.20", optional = true }
rustls-pemfile = { version = "0.3", optional = true }
time = { version = "0.3.7", features = ["parsing", "formatting", "macros"] }
tokio = { version = "1.17", features = ["rt", "io-util", "net", "fs", "sync", "parking_lot", "time"] }
webpki = { version = "0.22", optional = true }
x509-parser = { version = "0.13", optional = true }

[features]
default = ["full"]

# Enable all features
full = ["all-http", "all-compression", "graceful-shutdown", "auto-hostname", "nonce"]

# Compressing
all-compression = ["br", "gzip"]
br = ["brotli"]
gzip = ["flate2"]

# HTTP standards
all-http = ["https", "http2"]
https = ["rustls", "rustls-pemfile", "webpki"]
http2 = ["h2", "https"]

# Graceful shutdown; shutdown.rs
graceful-shutdown = []

# Automatic populating of Host name and alt-names
auto-hostname = ["x509-parser"]

# nonce implementation
nonce = ["rand", "base64", "memchr"]

# also add to https://kvarn.org/cargo-features.

[dev-dependencies]
kvarn_testing = { path = "testing", version = "0.3" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
