[package]
name = "kvarn"
version = "0.1.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2018"
homepage = "https://icelk.dev/kvarn/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "./",
  "kvarn_extensions",
  "kvarn_chute",
]

[dependencies]
rustls = "0.19"
tokio = { version = "1.2.0", features = ["rt-multi-thread", "net", "fs", "sync", "parking_lot"] }
webpki = "0.21"
log = "0.4.14"
http = "0.2"
mime = "0.3"
mime_guess = "2"
brotli = { version = "3.3", optional = true }
flate2 = { version = "1", optional = true }

[features]
default = ["compression", "fs", "limiting"]

# Enables the server to serve from the file system
fs = []
# Enables limits on the server, to avoid abusive usage by counting IP requests
limiting = []

# Disables the cache
no-fs-cache = []
no-response-cache = []
no-template-cache = []
no-cache = ["no-fs-cache", "no-response-cache", "no-template-cache"]

# Compressing
compression = ["br", "gzip"]
br = ["brotli"]
gzip = ["flate2"]
