[package]
name = "arktis"
version = "0.1.0"
authors = ["Iselk <62830417+Iselk@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.18.1"
http = "0.2.1"
mime_guess = "2.0.3"
mio = { version = "0.7.2", features = ["os-poll", "tcp"] }
num_cpus = "1.13.0"

[features]
default = ["templates", "php"]

# Enables the template extention
templates = []
# Enables PHP interpretation of files
php = []
# Disables the cache
no-cache = []
