[package]
name = "arktis"
version = "0.1.0"
authors = ["Icelk"]
edition = "2018"
homepage = "https://icelk.dev/arktis/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "./",
  "arktis_extensions",
]

[dependencies]
rustls = "0.18.1"
http = "0.2.1"
mime_guess = "2.0.3"
mio = { version = "0.7.2", features = ["os-poll", "tcp"] }
num_cpus = "1.13.0"
mime = "0.3.16"
brotli = { version = "3.3.0", optional = true }
flate2 = { version = "1.0.18", optional = true }

[features]
default = ["templates", "compression"]

# Enables the template extention
templates = []
# Enables PHP interpretation of files
php = []

# Disables the cache
no-fs-cache = []
no-response-cache = []
no-template-cache = []
no-cache = ["no-fs-cache", "no-response-cache", "no-template-cache"]

# Compressing
compression = ["br", "gzip"]
br = ["brotli"]
gzip = ["flate2"]
