[package]
name = "kvarn_testing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvarn = { path = "../", features = ["full"] }
reqwest = { version = "^0.11" }
rand = "^0.8"
rcgen = "^0.8"
tokio = { version = "^1.13", features = ["macros"] }
rustls = "^0.20"
