[package]
name = "kvarn_extensions"
version = "0.2.0"
authors = ["Icelk <main@icelk.dev>"]
edition = "2018"
description = "Extensions for the Kvarn web server. Features HTTP/2 automatic push and a templating engine."
repository = "https://github.com/Icelk/kvarn/tree/main/kvarn_extensions/"
license = "Apache-2.0"
keywords = ["http-push", "template", "php"]
categories = ["template-engine"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvarn = { path = "../", default-features = false }
fastcgi-client = { git = "https://github.com/Icelk/fastcgi-client-rs", optional = true }
tokio = { version = "^1.13", optional = true, features = ["net", "io-util"] }
url_crawl = { path = "../url_crawl", optional = true }
async_chunked_transfer = "^1.4"

[features]
default = ["php", "templates", "push"]
php = ["fastcgi-client", "tokio"]
templates = []
push = ["url_crawl"]
reverse-proxy = ["tokio"]

[dev-dependencies]
tokio = { version = "^1.13", features = ["net", "io-util", "macros"] }
kvarn_testing = { path = "../testing" }
