name: Chute Continuous Integration

on:
    push:
        paths:
            - "chute/**"
            - ".github/workflows/chute.yml"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: chute

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Checking out sources
              uses: actions/checkout@v1
            - uses: Swatinem/rust-cache@v1
            - name: Checking project will all features
              run: cargo clippy -- -D warnings

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Checking out sources
              uses: actions/checkout@v1
            - uses: Swatinem/rust-cache@v1
            - name: Compiling
              run: cargo rustc --release
            - name: Upload bin artefact
              uses: actions/upload-artifact@v2
              with:
                  name: chute
                  path: target/release/kvarn_chute
