name: Chute Continuous Integration

on:
    push:
        paths:
            - "chute/**"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: extensions

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Checking out sources
              uses: actions/checkout@v1
            - uses: Swatinem/rust-cache@v1
            - name: Installing clippy
              run: rustup component add clippy
            - name: Checking project
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: -- -D warnings

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Checking out sources
              uses: actions/checkout@v1
            - uses: Swatinem/rust-cache@v1
            - name: Compiling
              uses: actions-rs/cargo@v1
              with:
                  command: rustc
                  args: --release
            - name: Upload bin artefact
              uses: actions/upload-artifact@v2
              with:
                  name: chute
                  path: /target/release/kvarn_chute
