name: Chute Continuous Integration

on:
    push:
        paths:
            - "chute/**"
            - "utils/**"
            - ".github/workflows/chute.yml"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: chute

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v1
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: Swatinem/rust-cache@v1
            - name: Checking formatting
              run: cargo fmt -- --check
            - name: Checking lints
              run: cargo clippy --all-targets -- -D warnings

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v1
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
            - uses: Swatinem/rust-cache@v1
            - name: Compiling
              run: cargo rustc --profile distribution
            - name: Upload bin artefact
              uses: actions/upload-artifact@v2
              with:
                  name: chute
                  path: target/distribution/chute
