name: Extensions Continuous Integration

on:
    push:
        paths-ignore:
            - "chute/**"
            - "ctl/**"
            - "tests/**"
            - "testing/**"
            - ".github/workflows/chute.yml"
            - ".github/workflows/kvarnctl.yml"
            - ".github/dependabot.yml"
            - "README.md"
            - "roadmap.md"
            - "LICENSE"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: extensions

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v1
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: Swatinem/rust-cache@v1
            - name: Checking formatting
              run: cargo fmt -- --check
            - name: Checking lints with all features
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Checking lints with no features
              run: cargo clippy --no-default-features -- -D warnings
            - name: Checking doc references
              uses: Icelk/rustdoc-link-check@v1
              with:
                  private: true
                  working-directory: extensions
            - name: Testing project
              run: cargo test

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v1
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
            - uses: Swatinem/rust-cache@v1
            - name: Compiling
              run: cargo rustc --release -- --crate-type rlib
            - name: Upload rlib artefact
              uses: actions/upload-artifact@v2
              with:
                  name: libextensions.rlib
                  path: target/release/libkvarn_extensions.rlib
