name: Extensions Continuous Integration

on:
    push:
        paths:
            - "extensions/**"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: extensions

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Checking out sources
              uses: actions/checkout@v1
            - uses: Swatinem/rust-cache@v1
            - name: Installing clippy
              run: rustup component add clippy
            - name: Running rustfmt
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: -- --check
            - name: Checking project will all features
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --all-targets --all-features -- -D warnings
            - name: Checking doc references
              run: test -z "$(cargo doc --no-deps --document-private-items -q 2>&1 | head -n 1)"
            - name: Testing
              uses: actions-rs/cargo@v1
              with:
                  command: test

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Checking out sources
              uses: actions/checkout@v1
            - uses: Swatinem/rust-cache@v1
            - name: Compiling
              uses: actions-rs/cargo@v1
              with:
                  command: rustc
                  args: --release -- --crate-type rlib
            - name: List files
              run: ls -R
            - name: Upload rlib artefact
              uses: actions/upload-artifact@v2
              with:
                  name: libextensions.rlib
                  path: /home/runner/work/kvarn/kvarn/target/release/libkvarn_extensions.rlib
