name: Extensions Continuous Integration

on:
    push:
        paths-ignore:
            - "chute/**"
            - "ctl/**"
            - "testing/**"
            - ".github/workflows/chute.yml"
            - ".github/workflows/kvarnctl.yml"
            - ".github/dependabot.yml"
            - "README.md"
            - "CHANGELOG.md"
            - "roadmap.md"
            - "LICENSE"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: extensions

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v3
            - run: rustup toolchain install stable
            - uses: Swatinem/rust-cache@v2
            - name: Checking formatting
              run: cargo fmt -- --check
            - name: Checking lints with all features
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Checking lints with no features
              run: cargo clippy --no-default-features -- -D warnings
            - name: Checking doc references
              uses: Icelk/rustdoc-link-check@v2
              with:
                  private: true
                  working-directory: extensions
            - name: Testing project
              run: cargo test
