name: kvarnctl Continuous Integration

on:
    push:
        paths:
            - "ctl/**"
            - "utils/**"
            - ".github/workflows/kvarnctl.yml"

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
        working-directory: ctl

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v3
            - run: rustup toolchain install stable
            - uses: Swatinem/rust-cache@v2
            - name: Checking formatting
              run: cargo fmt -- --check
            - name: Checking lints
              run: cargo clippy --all-targets -- -D warnings

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v3
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - name: Compiling
              run: cargo rustc --profile distribution
            - name: Upload bin artefact
              uses: actions/upload-artifact@v2
              with:
                  name: kvarnctl
                  path: target/distribution/kvarnctl
