name: Continuous Integration

on:
    push:
        paths-ignore:
            - "extensions/**"
            - "chute/**"
            - "ctl/**"
            - "url_crawl/**"
            - ".github/workflows/chute.yml"
            - ".github/workflows/extensions.yml"
            - ".github/workflows/kvarnctl.yml"
            - ".github/dependabot.yml"
            - "README.md"
            - "CHANGELOG.md"
            - "roadmap.md"
            - "LICENSE"

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v3
            - run: rustup toolchain install stable
            - uses: Swatinem/rust-cache@v2
            - name: Check formatting
              run: cargo fmt --check
            - name: Checking lints with default features in workspace
              run: cargo clippy --workspace --exclude kvarn-extensions --all-targets -- -D warnings
            - name: Checking lints with default features
              run: cargo clippy --all-targets -- -D warnings
            - name: Checking lints with all features
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Checking lints with no features
              run: cargo clippy --no-default-features -F base -- -D warnings
            - name: Checking lints with embedded features
              run: cargo clippy --no-default-features -- -D warnings
            - name: Checking doc references
              uses: Icelk/rustdoc-link-check@v2
              with:
                  private: true
            - run: cargo test --workspace --exclude kvarn-extensions
