name: Continuous Integration

on:
    push:
        paths-ignore:
            - "extensions/**"
            - "chute/**"
            - "url_crawl/**"
            - ".github/workflows/chute.yml"
            - ".github/workflows/extensions.yml"
            - ".github/dependabot.yml"
            - "README.md"
            - "roadmap.md"
            - "LICENSE"

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v1
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - uses: Swatinem/rust-cache@v1
            - name: Checking formatting
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: -- --check
            - name: Checking lints
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --all-targets -- -D warnings
            - name: Checking lints with all features
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --all-targets --all-features -- -D warnings
            - name: Checking lints with no features
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --no-default-features -- -D warnings
            - name: Checking doc references
              uses: Icelk/rustdoc-link-check@v1
              with:
                  private: true
            - name: Testing project
              uses: actions-rs/cargo@v1
              with:
                  command: test
            - name: Testing kvarn-utils
              run: cargo test
              working-directory: utils
            - name: Testing kvarn-async
              run: cargo test
              working-directory: async
            - name: Testing kvarn-testing
              run: cargo test
              working-directory: testing
            - name: Testing kvarn_signal
              run: cargo test
              working-directory: signal
            - name: Testing url-crawl
              run: cargo test
              working-directory: url-crawl

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v1
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  profile: minimal
            - uses: Swatinem/rust-cache@v1
            - name: Compiling
              uses: actions-rs/cargo@v1
              with:
                  command: rustc
                  args: --release -- --crate-type rlib
            - name: Upload rlib artefact
              uses: actions/upload-artifact@v2
              with:
                  name: libkvarn.rlib
                  path: target/release/libkvarn.rlib
